###############################################################################
#     本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                          #
#        非商业性使用 — 不得将此项目用于任何商业和盈利用途                          #
###############################################################################
users:
  - user:
    username: "木羽" # 备注信息
    code: "" # 智慧川信临时code
    Cookie: ""
    InSchool: "不在校"
    GoOutYN: "不在广元，在省内"
    lat: '' # 维度
    lon: '' # 经度
