###############################################################################
#     本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                          #
#        非商业性使用 — 不得将此项目用于任何商业和盈利用途                          #
###############################################################################
users:
  - user:
    username: "" # 备注信息
    code: "" # 智慧川信code
    Cookie: ""
    Temperature: "" # 体温
    InSchool: "在校"
    GoOutYN: "在广元"
    lat: '32.418995' # 维度
    lon: '105.88456' # 经度
    qq_gid: "" # 推送的qq群号
